### ISSUE TITLE
Does this still work? Getting Broadcast has failed

### ISSUE THREAD

**Issue by notbrian** [tomcarbon/dogecoinmultisig#4]
Trying to send a test transaction between my accounts and I get this alert that pops up

```
The amount requested to be withdrawn has a higher
amount than the maximum allowed number of transactions
that this site allows.
Maybe one day there will be a consolidation feature, but that's not today.
However, there is a solution: 
We can use the first 60 transactions to pay a 
total of -20 to the output address.
(you can repeat with subsequent transaction(s) until the desired amount is paid.)
(you can also try to switch vendors: chain.so takes the earliest 99 transactions,
blockcypher.com takes the latest 60 transactions)
There will be no change transaction this time.
DO YOU STILL WISH TO PROCEED?
```

I click okay and then the transaction gets signed "Another Successful Sign!"

and then I click Broadcast and thats when I get `This broadcast has FAILED`

This is what I see in the console.
![image](https://user-images.githubusercontent.com/9014119/106322000-28b1bd80-6243-11eb-9d02-14b7792fc6de.png)

**Comment by tomcarbon** [comment]
Hi, yup, it should still work fine, API's operational. 

Sometimes that error will pop up for sandy accounts with a lot of tx, but that doesn't seem to be the case here. If you're using the same test accounts with coinb.in there's the possibility that the transaction is floating in limbo at blockcypher, if a mistake was made at coinb.in (this sucks). If that's not the case, you could try again with a slightly different amount of doge. Also, you can get more detailed log information in the console.log (F12 on most browsers).

**Comment by notbrian** [comment]
Yeah I'm not using any test accounts with coinb.in this is just my dogecoin multisig wallet I made awhile ago. Trying with different amounts of DOGE doesn't seem to change anything.

The only error messages I'm getting in the console are this 
```
Failed to load resource: the server responded with a status of 400 ()

moist.js:771 {
    "readyState": 4,
    "responseText": "{\"error\": \"Error validating transaction: Transaction missing input or output..\"}",
    "status": 400,
    "statusText": "error"
}
```

**Comment by notbrian** [comment]
When I verify the transaction I get this however, which isn't a valid address and the amount is extremely high.
![image](https://user-images.githubusercontent.com/9014119/106338612-30348f00-6262-11eb-8a39-e29d6ba6a426.png)

**Comment by tomcarbon** [comment]
What's the dogecoin address you are trying to pull from (feel free to DM if you prefer).

**Comment by tomcarbon** [comment]
if that's a transaction, it's quite corrupted.

**Comment by notbrian** [comment]
Sent you an email.

**Comment by tomcarbon** [comment]
got it. per our conv, looks like there's an issue with a transaction having multiple outputs (89+ outputs). I'll create and test a fix and let you know.

**Comment by tomcarbon** [comment]
fix has been vetted and moved into the main. thanks
